version: "3"
networks:
  dashboard-reference-network:
    external: true

services:
  fe:
    image: apache/doris:fe-3.0.4
    hostname: fe
    ports:
      - 8030:8030
      - 9030:9030
      - 9010:9010
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - FE_ID=1
    networks:
      - dashboard-reference-network

  be:
    image: apache/doris:be-3.0.4
    hostname: be
    ports:
      - 8040:8040
      - 9050:9050
    environment:
      - FE_SERVERS=fe1:172.20.80.2:9010
      - BE_ADDR=172.20.80.3:9050
    depends_on:
      - fe
    networks:
      - dashboard-reference-network