version: '3.8'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - dashboard-reference-network
    ports:
      - "9090:9090"

networks:
  dashboard-reference-network:
    external: true