apiVersion: 1

datasources:
  - name: Apache Doris
    type: mysql
    url: fe:9030
    database: web_monitoring
    user: root
    updateIntervalSeconds: 2
    secureJsonData:
      password: ''
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
    editable: true
