{
 "title": "Final Updated Benchmark",
 "time": { "from": "2025-07-18T10:42:45.000Z", "to": "2025-07-18T10:44:45.000Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Apache Doris", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingestion Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    { "expr": "rate(doris_be_load_rows[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Read Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(doris_be_query_scan_rows[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Query Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "doris_fe_query_latency_ms{user!~\"root|admin\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Stored Data",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "web_monitoring",
     "rawSql": "SELECT COUNT(*) FROM web_monitoring.web_server_logs"
    }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Kafka Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "rate(kafka_server_brokertopicmetrics_messagesin_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flink Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "max by(job_id) (flink_taskmanager_job_task_operator_numRecordsInPerSecond)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "End-to-End Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "End-to-End Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "SELECT\n  MIN(latency_sec) AS min_latency_seconds,\n  MAX(latency_sec) AS max_latency_seconds,\n  AVG(latency_sec) AS avg_latency_seconds,\n  PERCENTILE_APPROX(latency_sec, 0.5) AS p50_latency_seconds,\n  PERCENTILE_APPROX(latency_sec, 0.95) AS p95_latency_seconds,\n  PERCENTILE_APPROX(latency_sec, 0.99) AS p99_latency_seconds\nFROM (\n  SELECT\n    TIMESTAMPDIFF(SECOND, time, ingestion_time) AS latency_sec\n  FROM web_server_logs\n  WHERE time IS NOT NULL AND ingestion_time IS NOT NULL\n  ORDER BY ingestion_time ASC\n  LIMIT 2000\n) AS filtered;"
    }
   ]
  },
  {
   "title": "Flink Latency",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "__internal_schema",
     "rawSql": "SELECT\n  MIN(flink_processing_time_ms) AS min_latency_seconds,\n  MAX(flink_processing_time_ms) AS max_latency_seconds,\n  AVG(flink_processing_time_ms) AS avg_latency_seconds,\n  PERCENTILE_APPROX(flink_processing_time_ms, 0.5) AS p50_latency_seconds,\n  PERCENTILE_APPROX(flink_processing_time_ms, 0.95) AS p95_latency_seconds,\n  PERCENTILE_APPROX(flink_processing_time_ms, 0.99) AS p99_latency_seconds\nFROM (\n  SELECT flink_processing_time_ms\n  FROM web_server_logs\n  WHERE time IS NOT NULL AND ingestion_time IS NOT NULL\n  ORDER BY ingestion_time ASC\n  LIMIT 2000\n) as logs;"
    }
   ]
  },
  { "title": "Resources Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Usage per Container (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=~\"flink-java-flink-job-1|kafka-server-reference|zookeeper-reference|flume-agent|doris-be-1|doris-fe-1|web-server-reference-app|web-server-reference-db|web-server-reference-nginx|grafana\"}[5m]) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\"flink-java-flink-job-1|kafka-server-reference|zookeeper-reference|flume-agent|doris-be-1|doris-fe-1|web-server-reference-app|web-server-reference-db|web-server-reference-nginx|grafana\"} / 1024 / 1024",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}