version: '3.8'

services:
  web-server-reference-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-server-reference-app
    depends_on:
      - web-server-reference-db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.10

  web-server-reference-db:
    image: postgres:15
    container_name: web-server-reference-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/migrations
      - ./run-migrations.sh:/docker-entrypoint-initdb.d/01_run_migrations.sh
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.11

  nginx:
    image: nginx:latest
    container_name: web-server-reference-nginx
    depends_on:
      - web-server-reference-app
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - app-data:/var/log/nginx 
    restart: unless-stopped
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.12
  
  flume:
    build:
      context: ./flume
      dockerfile: Dockerfile.flume
    container_name: flume-agent
    depends_on:
      - nginx
    volumes:
      - ./flume/flume.conf:/flume/conf/flume.conf:ro
      - app-data:/var/log/nginx:ro 
      # - ./flume/jmx_exporter/jmx_exporter.yaml:/opt/flume/conf/jmx-exporter-config.yml
      # - ./flume/jmx_exporter/jmx_prometheus_javaagent-1.2.0.jar:/opt/flume/lib/jmx_prometheus_javaagent.jar
    environment:
      - FLUME_JAVA_OPTS=-Xms512m -Xmx1024m
      # - JAVA_TOOL_OPTIONS=-javaagent:/opt/flume/lib/jmx_prometheus_javaagent.jar=7071:/opt/flume/conf/jmx-exporter-config.yml
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.13

  # flume-exporter:
  #   build:
  #     context: ./flume-exporter
  #     dockerfile: Dockerfile
  #   container_name: flume-exporter
  #   depends_on:
  #     - flume
  #   environment:
  #     - FLUME_EXPORTER_PORT=8080
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     dashboard-reference-network:
  #       ipv4_address:

volumes:
  app-data: {}
  pgdata: {}

networks:
  dashboard-reference-network:
    external: true

