version: '3.7'
services:

  jobmanager-reference:
    image: flink:1.18
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.60
    ports:
      - 8081:8081
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager-reference"
    command: jobmanager

  taskmanager-reference:
    image: flink:1.18
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.61
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager-reference"
    command: taskmanager

  app-reference:
    image: flink-app
    build:
      context: .
    environment:
      KAFKA_BROKER: kafka-server-reference:9092
      KAFKA_TOPIC: nginx-logs
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      DORIS_JDBC_URL: jdbc:mysql://172.20.80.2:9030/web_monitoring
      DORIS_USERNAME: admin
      DORIS_PASSWORD: ""
      SINK_DIR: /sink
    depends_on:
      - jobmanager-reference
      - taskmanager-reference
    volumes:
      - ./sink:/sink
      # - ./flink_with_python/app.py:/taskscripts/app.py
    entrypoint:
      - tail
    command: 
      - -f
      - /dev/null
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.62

networks:
  dashboard-reference-network:
    external: true
