version: '3.7'
services:

  jobmanager-reference:
    image: flink:1.18
    build:
      context: .
      dockerfile: Dockerfile.flinkmanager
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.60
    ports:
      - 8081:8081
    environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager-reference
      metrics.reporters: prom
      metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
      metrics.reporter.prom.port: 9249
      taskmanager.numberOfTaskSlots: 2
      parallelism.default: 2
      python.client.executable: python3
      python.executable: python3
    command: jobmanager

  taskmanager-reference:
    image: flink:1.18
    build:
      context: .
      dockerfile: Dockerfile.flinkmanager
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.61
    environment:
    - |
      FLINK_PROPERTIES=
      jobmanager.rpc.address: jobmanager-reference
      metrics.reporters: prom
      metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
      metrics.reporter.prom.port: 9249
      taskmanager.numberOfTaskSlots: 2
      python.client.executable: python3
      python.executable: python3
    command: taskmanager

  app-reference:
    image: flink-app
    build:
      context: .
    environment:
      KAFKA_BROKER: kafka-server-reference:9092
      KAFKA_TOPIC: nginx-logs
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      DORIS_JDBC_URL: jdbc:mysql://172.20.80.2:9030/web_monitoring
      DORIS_USERNAME: admin
      DORIS_PASSWORD: ""
      SINK_DIR: /sink
    depends_on:
      - jobmanager-reference
      - taskmanager-reference
    volumes:
      - ./sink:/sink
      - ./flink_with_python:/flink_with_python
    entrypoint:
      - tail
    command: 
      - -f
      - /dev/null
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.62

networks:
  dashboard-reference-network:
    external: true
