version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper-reference
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.50

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-server-reference
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "7071:7071" 
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server-reference:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka-server-reference
    command:
      - bash
      - -c
      - >
        KAFKA_OPTS="-javaagent:/jmx_exporter/jmx_prometheus_javaagent-1.2.0.jar=7071:/jmx_exporter/jmx_exporter.yaml"
        /etc/confluent/docker/run
    volumes:
      - ./jmx_exporter:/jmx_exporter
    networks:
      dashboard-reference-network:
        ipv4_address: 172.20.80.51

networks:
  dashboard-reference-network:
    name: dashboard-reference-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.80.0/24

